import { ICategory } from '@/entities/categories/model/index';

export const categoriesList: Array<ICategory> = [
  {
    id: 1,
    workspaceId: 1,
    title: 'Welcome',
    slug: 'welcome',
    description: 'Welcome to Human resources workspace',
    categoryId: null,
  },
  {
    id: 2,
    workspaceId: 2,
    title: 'Welcome',
    slug: 'welcome',
    description: 'Welcome to Information technology workspace',
    categoryId: null,
  },
  {
    id: 3,
    workspaceId: 3,
    title: 'Welcome',
    slug: 'welcome',
    description: '',
    categoryId: null,
  },
  {
    id: 4,
    workspaceId: 4,
    title: 'Welcome',
    slug: 'welcome',
    description: '',
    categoryId: null,
  },
  {
    id: 5,
    workspaceId: 5,
    title: 'Welcome',
    slug: 'welcome',
    description: '',
    categoryId: null,
  },
  {
    id: 6,
    workspaceId: 6,
    title: 'Welcome',
    slug: 'welcome',
    description: '',
    categoryId: null,
  },
  {
    id: 7,
    workspaceId: 7,
    title: 'Welcome',
    slug: 'welcome',
    description: '',
    categoryId: null,
  },
  {
    id: 8,
    workspaceId: 8,
    title: 'Welcome',
    slug: 'welcome',
    description: '',
    categoryId: null,
  },
  {
    id: 9,
    workspaceId: 9,
    title: 'Welcome',
    slug: 'welcome',
    description: '',
    categoryId: null,
  },
  {
    id: 10,
    workspaceId: 10,
    title: 'Welcome',
    slug: 'welcome',
    description: '',
    categoryId: null,
  },
  {
    id: 11,
    workspaceId: 11,
    title: 'Welcome',
    slug: 'welcome',
    description: '',
    categoryId: null,
  },
  {
    id: 12,
    workspaceId: 12,
    title: 'Welcome',
    slug: 'welcome',
    description: '',
    categoryId: null,
  },
  {
    id: 13,
    workspaceId: 13,
    title: 'Welcome',
    slug: 'welcome',
    description: '',
    categoryId: null,
  },
]