export { useWorkspacesCreateMutation } from './useWorkspacesCreateMutation'
export { useWorkspacesDeleteMutation } from './useWorkspacesDeleteMutation'
export { useWorkspacesGetManyQuery } from './useWorkspacesGetManyQuery'
export { useWorkspacesGetQuery } from './useWorkspacesGetQuery'
export { useWorkspacesUpdateMutation } from './useWorkspacesUpdateMutation'
